#!/bin/sh

if [ -n "$(git status -s)" ]; then
  echo "Working tree is dirty, cannot bundle (try commiting changes)."
  exit 1
fi

entry="${1:-app.ts}"
outfile="${2:-ui}"

sed -i '/scss_auto_reload"$/d' $entry

ags bundle "$entry" "$outfile"

git restore .
