#!/bin/sh

entry="${1:-app.ts}"
outfile="${2:-astal-ui}"
backup="${3:-/tmp/entry.ts.bak}"

cp "$entry" "$backup"
sed -i '/scss_auto_reload"$/d' "$entry"
cp "$backup" "$entry"
rm "$backup"

ags bundle "$entry" "$outfile"
